export default [
  {
    belongDefault: false,
    icon: '',
    img: '/',
    isAvailable: false,
    menuId: 252,
    name: '应用导航',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [],
    path: '/thiredPartApp-1',
  },
  {
    belongDefault: false,
    icon: '',
    img: '',
    isAvailable: false,
    menuId: 253,
    name: '教务OA',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 301,
        name: '功能概述',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 0,
        subMenus: [],
      },
      {
        belongDefault: false,
        icon: 'line-chart',
        img: '',
        isAvailable: false,
        menuId: 254,
        name: '消息通知',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 1,
        subMenus: [],
        path: '/interaction/message',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 258,
        name: '考勤',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 2,
        subMenus: [
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 259,
            name: '考勤规则',
            parentMenuId: 258,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/security/setTimeRange',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 260,
            name: '考勤查询',
            parentMenuId: 258,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/security/workCheck',
          },
        ],
        path: '/security/setTimeRange',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 261,
        name: '公文流转',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 3,
        subMenus: [
          {
            belongDefault: false,
            icon: 'edit',
            img: '',
            isAvailable: false,
            menuId: 262,
            name: '新建公文',
            parentMenuId: 261,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/document/new',
          },
          {
            belongDefault: false,
            icon: 'edit',
            img: '',
            isAvailable: false,
            menuId: 263,
            name: '收件箱',
            parentMenuId: 261,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/document/inbox',
          },
          {
            belongDefault: false,
            icon: 'edit',
            img: '',
            isAvailable: false,
            menuId: 264,
            name: '发件箱',
            parentMenuId: 261,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/document/outbox',
          },
          {
            belongDefault: false,
            icon: 'edit',
            img: '',
            isAvailable: false,
            menuId: 265,
            name: '查询统计',
            parentMenuId: 261,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/document/statistics',
          },
        ],
        path: '/workOA/document',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 287,
        name: '物品报修',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 4,
        subMenus: [
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 288,
            name: '已处理',
            parentMenuId: 287,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/fix/process',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 289,
            name: '待处理',
            parentMenuId: 287,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/fix/pending',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 290,
            name: '数据分析',
            parentMenuId: 287,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/fix/analyse',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 291,
            name: '设置',
            parentMenuId: 287,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/fix/setting',
          },
        ],
        path: '/workOA/fix',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 292,
        name: '调查统计',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 5,
        subMenus: [
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 293,
            name: '调查列表',
            parentMenuId: 292,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/edumanage/survey/surveyList',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 294,
            name: '模板中心',
            parentMenuId: 292,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/edumanage/survey/template',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 295,
            name: '设置',
            parentMenuId: 292,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/edumanage/settingBase',
          },
        ],
        path: '/edumanage/survey',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 296,
        name: '工资条',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 6,
        subMenus: [
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 297,
            name: '工资条管理',
            parentMenuId: 296,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/salary/manage',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 298,
            name: '设置',
            parentMenuId: 296,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/salary/setting',
          },
          {
            belongDefault: false,
            icon: '',
            img: '',
            isAvailable: false,
            menuId: 299,
            name: '日志',
            parentMenuId: 296,
            shortcut: false,
            sortNum: 2147483647,
            subMenus: [],
            path: '/workOA/salary/logs',
          },
        ],
        path: '/workOA/salary',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 300,
        name: '微官网',
        parentMenuId: 253,
        shortcut: false,
        sortNum: 7,
        subMenus: [],
        path: '/microsite',
      },
    ],
    path: '/thiredPartApp-2',
  },
  {
    belongDefault: false,
    icon: '',
    img: '',
    isAvailable: false,
    menuId: 266,
    name: '人事管理',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 302,
        name: '功能概述',
        parentMenuId: 266,
        shortcut: false,
        sortNum: 0,
        subMenus: [],
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 268,
        name: '薪资管理',
        parentMenuId: 266,
        shortcut: false,
        sortNum: 1,
        subMenus: [],
        path: '/workOA/salary/manage',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 270,
        name: '调离管理',
        parentMenuId: 266,
        shortcut: false,
        sortNum: 2,
        subMenus: [],
        path: '/v2-aa',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 271,
        name: '档案管理',
        parentMenuId: 266,
        shortcut: false,
        sortNum: 3,
        subMenus: [],
        path: '/v2-bb',
      },
    ],
    path: '/thiredPartApp-3',
  },
  {
    belongDefault: false,
    icon: '',
    img: '',
    isAvailable: false,
    menuId: 272,
    name: '教育督导',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 303,
        name: '功能概述',
        parentMenuId: 272,
        shortcut: false,
        sortNum: 0,
        subMenus: [],
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 273,
        name: '教育满意度调查系统',
        parentMenuId: 272,
        shortcut: false,
        sortNum: 1,
        subMenus: [],
        path: '/workOA/salary/manage',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 274,
        name: '责任督学管理系统',
        parentMenuId: 272,
        shortcut: false,
        sortNum: 2,
        subMenus: [],
        path: '/v2-aa',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 275,
        name: '学校发展性评价系统',
        parentMenuId: 272,
        shortcut: false,
        sortNum: 3,
        subMenus: [],
        path: '/v2-bb',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 276,
        name: '均衡发展监测系统',
        parentMenuId: 272,
        shortcut: false,
        sortNum: 4,
        subMenus: [],
        path: '/v2-cc',
      },
    ],
    path: '/thiredPartApp-4',
  },
  {
    belongDefault: false,
    icon: '',
    img: '',
    isAvailable: false,
    menuId: 277,
    name: '招考管理',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 304,
        name: '功能概述',
        parentMenuId: 277,
        shortcut: false,
        sortNum: 0,
        subMenus: [],
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 278,
        name: '招生管理',
        parentMenuId: 277,
        shortcut: false,
        sortNum: 1,
        subMenus: [],
        path: '/workOA/salary/manage',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 279,
        name: '考试管理',
        parentMenuId: 277,
        shortcut: false,
        sortNum: 2,
        subMenus: [],
        path: '/v2-aa',
      },
    ],
    path: '/thiredPartApp-5',
  },
  {
    belongDefault: false,
    icon: '',
    img: '',
    isAvailable: false,
    menuId: 280,
    name: '教育扶贫',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 305,
        name: '功能概述',
        parentMenuId: 280,
        shortcut: false,
        sortNum: 0,
        subMenus: [],
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 281,
        name: '教育扶贫',
        parentMenuId: 280,
        shortcut: false,
        sortNum: 1,
        subMenus: [],
        path: '/workOA/salary/manage',
      },
    ],
    path: '/thiredPartApp-6',
  },
  {
    belongDefault: false,
    icon: '',
    img: '',
    isAvailable: false,
    menuId: 282,
    name: '数据看板',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 306,
        name: '功能概述',
        parentMenuId: 282,
        shortcut: false,
        sortNum: 0,
        subMenus: [],
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 283,
        name: '区县数据看板',
        parentMenuId: 282,
        shortcut: false,
        sortNum: 1,
        subMenus: [],
        path: '/workOA/salary/manage',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 284,
        name: '学校数据看板',
        parentMenuId: 282,
        shortcut: false,
        sortNum: 2,
        subMenus: [],
        path: '/v2-aa',
      },
      {
        belongDefault: false,
        icon: '',
        img: '',
        isAvailable: false,
        menuId: 285,
        name: '学生数据看板',
        parentMenuId: 282,
        shortcut: false,
        sortNum: 3,
        subMenus: [],
        path: '/v2-bb',
      },
    ],
    path: '/thiredPartApp-7',
  },
  {
    belongDefault: false,
    icon: '',
    img: '',
    isAvailable: false,
    menuId: 286,
    name: '通讯录',
    parentMenuId: 0,
    shortcut: false,
    sortNum: 2147483647,
    subMenus: [],
    path: '/addressBook',
  },
];
